# Latihan 1

In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [5]:
arr = np.append(arr, [1, 2])
print(arr)

[1 2 3 4 5 6 7 8 1 2]


In [6]:
arr = np.delete(arr, 1)
print(arr)

[1 3 4 5 6 7 8 1 2]


In [7]:
arr = np.sort(arr)
print(arr)

[1 1 2 3 4 5 6 7 8]


# Latihan 2

In [9]:
ex = np.array([[[1, 2, 3, 4],[5, 6, 7, 8]],[[9, 10, 11, 12],[13, 14, 15, 16]],[[17, 18, 19, 20],[21, 22, 23, 24]]])
print(ex)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [12]:
print(ex.ndim)
print(ex.size)
print(ex.shape)

3
24
(3, 2, 4)


# Latihan 3

In [14]:
ex2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
print(ex2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [15]:
print(ex2.reshape(3, 2, 4))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


# Latihan 4

In [16]:
ex3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(ex3.shape)

(12,)


In [17]:
ex4 = ex3[np.newaxis]
print(ex4.shape)
print(ex4)

(1, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [19]:
ex5 = ex3[:,np.newaxis]
print(ex5.shape)
print(ex5)

(12, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [23]:
ex6 = np.expand_dims(ex5, axis = 1)
print(ex6.shape)
print(ex6)

(12, 1, 1)
[[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]]


# Latihan 5

In [24]:
a1 = np.array([[11, 12, 13, 14],[15, 16, 17, 18],[19, 20, 21, 22],[23, 24, 25, 26],[27, 28, 29, 30]])
print(a1)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]


In [26]:
print(a1[a1 >= 13])

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [27]:
a2 = (a1 >= 10)
print(a1[a2])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [29]:
print(a1[a1 % 3 == 0])
print(a1[a1 % 2 == 1])
print(a1[a1 % 2 == 0])

[12 15 18 21 24 27 30]
[11 13 15 17 19 21 23 25 27 29]
[12 14 16 18 20 22 24 26 28 30]


In [32]:
a3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
aa = a3[5:7]
print(aa)

[6 7]


# Latihan 6

In [33]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [34]:
print(np.vstack((a1, a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [36]:
print(np.hstack((a1, a2)))

[[1 1 3 3]
 [2 2 4 4]]


In [40]:
x1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 , 20, 21, 22, 23, 24])
x2 = np.hsplit(x1, 4)
x3 = x1.view()
x4 = x1.copy()
print(x1)
print(x2)
print(x3)
print(x4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18]), array([19, 20, 21, 22, 23, 24])]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
