# Numpy Introduction

## Installing NumPy

In [1]:
conda install numpy
# atau
# pip install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Farah\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.10.3               |   py38haa95532_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:


Note: you may need to restart the kernel to use updated packages.


Did not find path entry C:\Users\Farah\anaconda3\bin


  conda                                4.9.2-py38haa95532_0 --> 4.10.3-py38haa95532_0




conda-4.10.3         | 2.9 MB    |            |   0% 
conda-4.10.3         | 2.9 MB    |            |   1% 
conda-4.10.3         | 2.9 MB    | 7          |   7% 
conda-4.10.3         | 2.9 MB    | #8         |  19% 
conda-4.10.3         | 2.9 MB    | ###1       |  32% 
conda-4.10.3         | 2.9 MB    | ####4      |  44% 
conda-4.10.3         | 2.9 MB    | #####7     |  58% 
conda-4.10.3         | 2.9 MB    | ######7    |  68% 
conda-4.10.3         | 2.9 MB    | #######7   |  77% 
conda-4.10.3         | 2.9 MB    | ########7  |  88% 
conda-4.10.3         | 2.9 MB    | ########## | 100% 
conda-4.10.3         | 2.9 MB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


## How to import NumPy

In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
print(a[0])

[1 2 3 4]


## Creating Array

In [8]:

import numpy as np
a = np.array([1, 2, 3])

In [9]:
a

array([1, 2, 3])

In [10]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# the function empty creates an array whose initial content is random and depends on the state of the memory
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.empty(6)

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       2.12199579e-313, 2.54639495e-313])

In [16]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
print(np.arange(4))
print(np.arange(0, 10, 2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [20]:
np.arange(2, 19, 5)

array([ 2,  7, 12, 17])

## Add, Remove, and Sort

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.append([1, 2], arr)

array([1, 2, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [27]:
arr = np.array([2, 1, 7, 5, 4, 6, 8, 3])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [29]:
array_example = np.array([[[0, 1, 2, 3],
[4, 5, 6, 7]],

[[0, 1, 2, 3],
[4, 5, 6, 7]],

[[0, 1, 2, 3],
[4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [30]:
array_example.ndim

3

In [31]:
array_example.size

24

In [32]:
array_example.shape # (dimensi, kolom, baris)

(3, 2, 4)

In [33]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [35]:
arr_one.ndim

2

In [36]:
arr_one.size

5

In [37]:
arr_one.shape

(1, 5)

## Reshape

In [39]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [43]:
b = a.reshape(3, 2) # (baris, kolom)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [44]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [45]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [47]:
# add a new axis
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [49]:
print(a[np.newaxis].shape)

(1, 6)


In [50]:
# convert a 1D array to a row vector by inserting an axis along the first dimension
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [53]:
# for a column vector, insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)


(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [54]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [55]:
# add an axis at index position 1 with:
b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [57]:
# add an axis at index position 0 with:
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

## Indexing and Slicing

In [60]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])
print(data[-1:])
print(data[-3:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]
[3]
[1 2 3]


In [62]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
print(a[a>=5])
print(a[a>=7])

[ 5  6  7  8  9 10 11 12]
[ 7  8  9 10 11 12]


In [65]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [67]:
# select elements that are divisible by 2
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [68]:
# select elements that satusfy two conditions using the & and | operators
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6 , 7, 8, 9, 10])

In [73]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [77]:
a_1 = np.array([[1, 1], [2, 2]])
a_2 = np.array([[3, 3], [4, 4]])
print(a_1)
print(a_2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [78]:
# menumpuk array secara vertikal
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [79]:
# menumpuk array secara horizontal
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [85]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]


In [87]:
# split array into three equally shaped arrays
np.hsplit(arrsplit, 3)

[array([[1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24]])]

In [88]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
# create a new array object that looks att the same data
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
# using the copy method will make a complete copy of the array and its data (a deep copy)
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operations

In [91]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [92]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [93]:
# sum the rows
b.sum(axis = 0)

array([3, 3])

In [94]:
# sum the columns
b.sum(axis = 1)

array([2, 4])

In [96]:
data = np.array([1, 2])
data

array([1, 2])

In [98]:
ones = np.ones(2)
ones

array([1., 1.])

In [99]:
data + ones

array([2., 3.])

In [101]:
data * data

array([1, 4])

In [102]:
data / data

array([1., 1.])

## Broadcasting

In [104]:
data * 2

array([2, 4])

## More Array Operations

In [113]:
A = np.array([[0.45, 0.17, 0.34, 0.55], [0.54, 0.05, 0.40, 0.55], [0.12, 0.82, 0.26, 0.56]])
print(A)

[[0.45 0.17 0.34 0.55]
 [0.54 0.05 0.4  0.55]
 [0.12 0.82 0.26 0.56]]


In [114]:
A.sum()

4.8100000000000005

In [115]:
A.min()

0.05

In [116]:
A.min(axis = 0)

array([0.12, 0.05, 0.26, 0.55])

In [117]:
A.max()

0.82

In [118]:
A.max(axis = 1)

array([0.55, 0.55, 0.82])

In [120]:
A.std()

0.21332519515727366

## Creating Matrices

In [122]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [123]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [128]:
no.random.random((3, 2))

array([[0.78944742, 0.53896726],
       [0.54474672, 0.21523668],
       [0.54634555, 0.46508796]])

## Matrix Arithmatic

In [129]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [130]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [131]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [133]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [135]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [136]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [137]:
a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [138]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matriks Indexing

In [140]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[2])
print(data[0, 1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [142]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [143]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [144]:
print(data.max(axis = 0))
print(data.max(axis = 1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [145]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [146]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [148]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [149]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [155]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [157]:
ndarr = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [158]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [161]:
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [162]:
print(np.random.random((4, 3, 2)))

[[[0.48330038 0.18708856]
  [0.07167374 0.46576918]
  [0.81253277 0.78876646]]

 [[0.61328622 0.56526781]
  [0.98729292 0.76670531]
  [0.73100844 0.71159609]]

 [[0.68321596 0.12303183]
  [0.38088736 0.20939843]
  [0.08896702 0.32208648]]

 [[0.09685576 0.68400569]
  [0.57773548 0.65918236]
  [0.02595406 0.18073377]]]


## Flatten N-Dimensional Array

In [163]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [164]:
# flatten array into a 1D array
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [166]:
# rumus mean square error
# error = (1/n) * np.sum(np.square(observed - prediction))

# TipsPy

## Notes on Numpy Vector

In [169]:
a = np.random.rand(5)
print(a)

[0.32379991 0.51429882 0.66543842 0.08355711 0.7816748 ]


In [171]:
a.shape # rank 1 array

(5,)

In [172]:
# akan tetap sama jika di transpose
print(a.T) 

[0.32379991 0.51429882 0.66543842 0.08355711 0.7816748 ]


In [174]:
# tidak menunjukkan hasil yg seharusnya jika di dot
print(np.dot(a, a.T))

1.4301552384328466


In [176]:
# Tips: selalu memasukkan 2 argumen ketika akan membuat column/row vector
a = np.random.rand(5,1)
print(a)

[[0.52472239]
 [0.81497584]
 [0.36929558]
 [0.75643312]
 [0.46608211]]


In [178]:
print(a.T)

[[0.52472239 0.81497584 0.36929558 0.75643312 0.46608211]]


In [179]:
print(np.dot(a, a.T))

[[0.27533359 0.42763607 0.19377766 0.39691739 0.24456372]
 [0.42763607 0.66418562 0.30096698 0.61647471 0.37984566]
 [0.19377766 0.30096698 0.13637923 0.27934741 0.17212206]
 [0.39691739 0.61647471 0.27934741 0.57219106 0.35255994]
 [0.24456372 0.37984566 0.17212206 0.35255994 0.21723253]]


In [182]:
a = np.random.rand(1, 5) #row vector
print(a)

[[0.85724195 0.76935324 0.94732937 0.21269261 0.07163639]]


In [ ]:
# Don't use rank 1 Array
# Always use 1 by n matrices or n by 1 matrices instead